### ISSUE TITLE
Possible abstraction for class Candle

### ISSUE THREAD

**Issue by LadislavBohm** [lppkarl/Trady#10]
Hello and thanks for this awesome library!

I might have a suggestion that could help me better integrate this library into my application. It seems that most if not all indicators depend somehow on class Candle or delegate mapper to select proper values.

Hower when dealing with large collections I have to convert my data objects to Candles which creates a lot of unnecessary allocations. It would be better if I could loosely depend on this libary by using some interface like this:

```
public interface IOhlcData
{
    DateTime DateTime { get; }

    decimal Open { get; }

    decimal High { get; }

    decimal Low { get; }

    decimal Close { get; }
}
```

I would then just implement it and use my own business objects without much or any modifications.
Thanks for considering and if you find it suitable I think I can create a pull request with such modification.

**Comment by lppkarl** [comment]
@LadislavBohm thanks for your suggestion, and i think it's a good one! But since the Candle class is distributed everywhere in the library, i suppose there will be an enormous work for replacing Candle and IndexedCandle (derived type of Candle) to IOhlcData/ IOhlcvData. If you could manage to make a PR of it, it would be really nice 👍

**Comment by LadislavBohm** [comment]
Already working on it, ill probably make PR today or tomorrow.
