### ISSUE TITLE
Consider Using DateTimeOffset Instead of DateTime

### ISSUE THREAD

**Issue by Mike-EEE** [lppkarl/Trady#15]
I've been going over my code and have been moving over my "ticks" or "candles" to `Trady.Core.Candle`.  However, I just noticed that the "tick" is a `DateTime` rather than a `DateTimeOffset`.  From my understanding, `DateTimeOffset`s are preferred as they contain timezones and save a lot of additional work (in theory?).  

Anyways, I was wondering what the feeling is on updating the `ITick.DateTime` field to be a `DateTimeOffset` instead.

**Comment by lppkarl** [comment]
@Mike-EEE Sorry for the late response. You've made a good argument on using DateTimeOffset rather than using DateTime. 

To be honest, I didn't think of it when I initially created this library, I was focusing on implementing indicators & the rule system. This library is now heavily rely on DateTime, but I agree that it should be a change to work around with the timezone problem. The only problem is there may be a large code change of it 🤣

**Comment by Mike-EEE** [comment]
Hey no worries @lppkarl.  It's definitely a breaking change.  However, `DateTimeOffset` has an implicit casting operator for `DateTime`, so a lot of referencing code will continue to work as-is.

**Comment by lppkarl** [comment]
@Mike-EEE Thanks for your reminder! I'll arrange it later.

**Comment by lppkarl** [comment]
@Mike-EEE I have just released a beta-version on this issue, just let you know 😄

**Comment by Mike-EEE** [comment]
Great!  Thank you @lppkarl !

**Comment by Mike-EEE** [comment]
Works like a champ, @lppkarl!  Thanks again. 👍
