### ISSUE TITLE
Integrate DateTime back to indicator result

### ISSUE THREAD

**Issue by lppkarl** [lppkarl/Trady#3]
Refer to: https://github.com/lppkarl/Trady/pull/2

**Comment by fernaramburu** [comment]
@lppkarl Hi, I have a commit to do with my suggested implementation and a test I just finished but it's too late here (1AM) to commit it  and then explain you what I did. Tomorrow  morning I do the commit and write some explanations but at a first sight it looks pretty amazing and pretty simple.

**Comment by fernaramburu** [comment]
@lppkarl Hi, I just commit some code on the branch you created. The code is tested on two simple scenarios, Simple Moving Average as a simple indicator and another indicator as the ones I'm trying to build: ClosePricePercentageChangeSinceMondayOpen. This indicator calculates the price percentage change since Open value of the Monday of the same week of that date. It would be something like a Week To Date calculation based on Monday Open Value instead of close or previous Friday close value.
Implementation of that indicator is in CustomIndicatorTest file on the test project and implementation could be done better as it suppose that we always have values for mondays and that mondays are never holiday, but I just wanted to implement something so you can get and idea of the way of implementing this behavior by mixing the previous implementation (v1.0) and the new one (v2.0).

All code is horribly typed with a 2 at the end (AnalyzableBase2, IAnalyzable2, SimpleMovingAverage2) as I just wanted you to see it before doing a big change as I saw lot of build issues as soon as I changed Interface IAnalyzable. 

I coded SMA indicator as well in SimpleMovingAverage2. You'll see 4 cases in that file not because I'm a mess coding but because I wanted to keep it simple and easy to view. If you think implementation is ok then we'll change and organize the code in the natural right way.  :)

In SimpleMovingAverage2 there are four clases. First SimpleMovingAverage2 as a Class, that's the actual indicator. It's generic with a TInput (following the nice naming of your code) and it produces decimal as results. As we need to convert TInput to decimal we used a mappingFunction from TInput to get the decimal.
Logic is the exact same place as in your Indicators code (ComputeByIndexImpl) and I just call the mapping function there to get the decimals.

Inside that class, as static methods, I provide to simple scenarios of SimpleMovingAverage from Candles and from decimal so you see concrete Indicator implementation through methods.

After that class I created two different classes to implement Candle and Decimal SimpleMovingAverage as a Class just to show that they can be easily and quickly implemented through Class inheritance by just calling the base constructor.

At the end of that file, I coded static class CandleExtension with simple methods to extend IEnumerable<Candle> and IEnumerable<decimal> as you did in your implementation to get same results.

I hope you like the idea, let's discuss. I'm completely open to hear your thoughts and possible changes. I think results were better and more simple than I originally expected  but I'm completely open to changes and even for being rejected :)

Thanks

Fer

**Comment by lppkarl** [comment]
@fernaramburu , thanks for the commit, I have read your code, it seems we have a different approach on the problem. You are trying to integrate the mapping function inside the indicator & do the computation together with the mapping internally while i am doing it externally outside the original indicator. I must say your approach is better than mine in terms of performance, there's no longer need to create another instance just for the computation. Quite nice :)

However, the input mapping function is not generic to other indicators. E.g. sma intakes decimal as the input type but obv intakes (Close, Volume) tuple as the input type. It requires us adding another generic arguments to the AnalyzableBase in order to intakes input mapping function generically.

We could also add output mapping function on AnalyzableBase, because I would like to get the v1 interface back. I.e. if input type is a candle, the output type should be with datetime (AnalyzableTick). Inspired by using an input map, i have also implemented a output map for this purpose.

I have implemented the above, and make some adjustment from it:

1. I have trimmed out the facilitators because it seems the method call is too long for instantiation & there's the extension method that does similar things.

2. Modify the signature of ComputeByIndex method, it now intakes the mapped input array & the index for computation. "Inputs" object is moved away from the scope of the method, because i want to de-couple the method from the object state ("Input") as far as possible. It makes code more mainteinable.

3. I have also renamed some classes. It's wise to keep the name SimpleMovingAverage for the Sma class who intakes candle as its input, because the lib is designed in this way along the road. The one who intakes decimal/tuple is renamed as SimpleMovingAverageByTuple, it's the most descriptive but short word i can name it.

Please take a look on the commit, and see if you agree on that, and if there's some other suggestion or some changes you want to make, please also make another commit on that. We can further discuss with that :)

**Comment by fernaramburu** [comment]
@lppkarl Hey, I haven't had time to review what you did but I was thinking that maybe we should choose output format instead of being as generic as you mentioned as we may need 4 generic types instead and it will get much harder if we continue to add features. What do you think?

I think we may define output between two or three different formats. We select which one and we tight all future developments to that until we need change for some reason.
About outputs, I was thinking we have different options:
1) dynamic/unnamed types. Those you are using in v2.0 that you do things like (decimal? Value1, decimal? Value2) just to give an example.
2) class as you had in v1.0 where we you had all the Result classes with the output of each indicator.
3) AnalyzableTick with the dateTime as part of the result. Pro: you have Datetime in the output so you can ask by date. Cons: you have to build an object for simple outputs as SMA.
4) The result, with and extra reference for the source object that generated the output. My idea is something similar to what you did in the AnalyzableTick but instead of adding the dateTime  you add a reference to the entire source object. So, if you call it with decimals you have a reference back to the source decimal and if you added candles then you have a reference to the candle, so to the datetime and other info you may need. Pros: easy to implement a change from AnalyzableTick as it's almost the same. Pro: we just use TInput and TOutput and the mappingFunction to get the values needed. Cons: complex result as SMA for example will not be just the decimal but a another ref (as in option 3) to the source object.

If I have to choose I would choose the simplest solution as in #1 or #2 or #4 where we get everything from the input and not just the DateTime. From my needs in #1 or #2 are ok and enough but you know your needs so you tell me :)

Thanks

Fer

**Comment by lppkarl** [comment]
@fernaramburu , just have an edit on your comment to prevent it referencing other issues in our project :)

For the output/return type, the last commit is an implementation of no.3, and it covers the cases of no.1 & no.2. To be simple, what i wanted to do is only the following two:
- If input is decimals/tuples, output is decimals/tuples. (i.e. IEnumerable\<decimal> -> IList\<decimal>)
- If input is candles, output is AnalyzableTick\<T> where T: decimal/tuple (i.e. IEnumerable\<Candle> -> IList\<AnalyzableTick\<T>>)

The first one is trivial, nothing special to take about.

For the second one, I would like it to happen because:
1. I want my input & output to be symmetric. If the input provides datetime, it's natural we have the datetime in our output. I consider our indicator as a mapping of a time-series to another time-series, datetime is crucial to both of them.

2. I used generic here because I have experienced how redundant it is to create a new IndicatorResult class for each indicator. It's good to see that the IndicatorResults shares the same property "DateTime", plus some "Values". AnalyzableTick\<T> is designed here to provide a general form of IndicatorResult, e.g. SimpleMovingAverage.IndicatorResult -> AnalyzableTick<decimal?>. It greatly reduce code redundancy, and it makes codes more readable.

3. On application, for graph plotting to be precise, it's essential for us to provide information for both x-axis & y-axis. If we are plotting graphs for the indicator results, it requires us to use both input & output arrays because we need to get the datetime from the input & the values from the output if we do not include datetime to the output, it's indeed inconvenient.

That's my points on including datetime back to the output, please let me know if there's some point you want me to make clarification. I'm open to any change and suggestions, thanks :)

P.S. This project is not urgent to work on, just work/reply when you're spare, take your time bro :)

**Comment by fernaramburu** [comment]
@lppkarl ajajaj, you are as obsessive as I am :) In a good sense I mean. I was going to edit my post due to the use of # and making references to other issues but as I was in a hurry I didn't do it but I was extremely close to do it :)

I like your approach and I fully agree with your points. I only disagree a bit with the output being AnalyzableTick as it could be something with more value as reflecting the entire source item (a Candle for example).

 I know it's not urgent but in someway it is as I'm trying to build something to show in October and I'm a bit far away (and delayed) from where I wanted to be, so I have some pressure for myself :)

I will review your code and see if I can find something a bit more spectacular from what we have now (simple and spectacular) :)

thanks!

Fer

**Comment by lppkarl** [comment]
@fernaramburu, good to know you agree on that :)

I agree that adding the source candle in AnalyzableTick\<T> is convenient for some developers, as it's easy to come up with something like "result.SourceCandle.Open" when they want to get the open price of the source candle on that day. 

But there may be concern in memory management if the lib is used in a low memory environment or the candle list is gigantic. As you may know, garbage collector does not collect the object as long as the object is referenced by the others. Correspondingly, if we are referencing the source candle in our AnalyzableTick\<T> object, there will be no recycling on the source candles when there's shortage of memory, it slows down or even crash because of memory shortage.

However, it's ok we add a parameter on AnalyzableBase\<T> to let user to choose whether to include a reference of the source candle for a AnalyzableTick\<T> instance, that should be a good approach to both side of the developers :)

**Comment by fernaramburu** [comment]
Such a good point you bring!!! I haven't thought before on running this in a low memory environment... You win! Let's leave it as it is now if you agree. It's quite extensible and quite configurable.  Will you do the coding for that change? I mean, I do those AnalyzableBase2 , SMA2 and everything with a 2 but we'll need to do a refactoring so everything use the new features and remove all the 2s.

By the way, I will be creating other issue about IndexedCandle and Porfolio backtesting that I want to discuss.

**Comment by lppkarl** [comment]
@fernaramburu ya, we can start the coding now. You do all those with a 2 and i will refactor & remove all the 2s after you've completed :)

**Comment by fernaramburu** [comment]
Perfect! will do that!
Can I also change, as we will be doing a massive file change, all IList<T> to IEnumerable<T>?

**Comment by wind-rider** [comment]
Unfortunately Deedle is not .net standard and it seems untouched for a year :/ otherwise it looked interesting to represent timeseries.
https://github.com/BlueMountainCapital/Deedle

**Comment by lppkarl** [comment]
@fernaramburu sure. There's also ILists in Core & Importer project, I'll handle those :)

@wind-rider interesting to know there's library for series manipulation, I am curious what features impressed you the most for using the lib, we may have some inspiration from it :)

**Comment by lppkarl** [comment]
@fernaramburu hi, it's been a month since our discussion. How's going with the implementation? Do you need help on the implementation, I am spare now and I may help to implement the feature, please tell me if you needs help :)

**Comment by fernaramburu** [comment]
Hey, sorry!!! It's been a terrible month for me. I started but suddenly I ran out of time and I didn't have time to go back to work there. I definetely should back there. Would you like to do that change? Would you like I commit the small part I did? Would you like we find the way ti work together there?

**Comment by lppkarl** [comment]
@fernaramburu nvm, take your time bro! You could just commit what you've implemented. I will do the rest :)

**Comment by lppkarl** [comment]
@fernaramburu As you're busy with your work, I would rather not give too much pressure on you. I have worked it on my own and have commit the changes, you may stop the coding :) The code is not tested yet but I will test it later.

**Comment by fernaramburu** [comment]
@lppkarl guau!!! Incredibly fast!!! Amazing! I will check what you did, If I have time over the weekend I might try to do some testing there at least, to help you.

**Comment by lppkarl** [comment]
@fernaramburu I have recently updated the lib to v3, and added some features on signal capturing & indicator/rule dynamic generation, it would be nice if you could comment on, or give ideas on it especially for the signal capturing part :)

By the way, this issue is addressed in v3, it will be closed now.

**Comment by fernaramburu** [comment]
@lppkarl guauuu!!! Unbelievable what you did!!! I will take a deep review on the latest release and I will probably enjoy de results.
I have some ideas that we can further discuss to extend this open source library that points to run in live mode and collects information for better and automated decision making.
