### ISSUE TITLE
Negative numbers in result.Transactions[x].Quantity

### ISSUE THREAD

**Issue by irperez** [lppkarl/Trady#70]
I'm seeing negative numbers consistently in the Quantity field in the Transactions after a back test run.  See below.  

![image](https://user-images.githubusercontent.com/1376080/45727677-bcaeed00-bb92-11e8-823a-7b2b49e9e071.png)

And this is the builder code to set things up.

![image](https://user-images.githubusercontent.com/1376080/45729663-832eaf80-bb9b-11e8-9a31-5bfc6201402c.png)

**Comment by lppkarl** [comment]
@irperez The case happens because the Fee parameter is misused in the builder, the fee here is used for currency exchange when use foreign currency to buy stock, it should be the fee for exchange, and should be a rate (between 0 and 1).

To clarify the use case, I've renamed those method in the Builder class, 'Fee' is changed to 'FlatExchangeFeeRate', 'BuyCompleteCurrencies' is changed to 'BuyWithAllAvailableCash', and moved premium to the Builder class.

The document has also been updated for the case, you can also refer the case there.

**Comment by irperez** [comment]
That makes a ton more sense.  We should put validation so that the Fee is only ever between 0 and 1.

**Comment by irperez** [comment]
Is there a way to track transaction costs per trade?

**Comment by lppkarl** [comment]
The cost are not currently added into each Transaction object, but should be easy to implement, you can study Runner.cs line number 101-147 for creation of Transaction object.

**Comment by irperez** [comment]
Ok, I'll see if I can make a PR for this.

**Comment by lppkarl** [comment]
@irperez Would like to confirm if it has been implemented or abandoned? Thanks.

**Comment by irperez** [comment]
@lppkarl I've put in a PR for this one.  Sorry it took so long.

**Comment by lppkarl** [comment]
@irperez it's ok, just want to confirm it's done. Thanks 👍
